### ISSUE TITLE
Some libraries don't seem to have version 0.12.0

### ISSUE THREAD

**Issue by babaosoftware** [tomtom-international/tomtom-navigation-android-examples#38]
Upon upgrading to 0.12.0 from 0.3.1617, the following libraries are not found:
Failed to resolve: com.tomtom.sdk.location:provider-map-matched:0.12.0
Failed to resolve: com.tomtom.sdk.navigation:navigation:0.12.0
Failed to resolve: com.tomtom.sdk.navigation:ui:0.12.0
Failed to resolve: com.tomtom.sdk.navigation:ui:0.12.0
Failed to resolve: com.tomtom.sdk.search:search:0.12.0
Failed to resolve: com.tomtom.sdk.search:additional-data-online:0.12.0
<img width="1572" alt="Screenshot 2023-05-20 at 12 29 19 PM" src="https://github.com/tomtom-international/tomtom-navigation-android-examples/assets/8468554/9fcf3da6-e88b-412a-9324-18cb89585af5">

**Comment by babaosoftware** [comment]
Seems that search:search-online:0.12.0 and search:ui:0.12.0 are now being resolved. There's still 4 more libraries that cannot be resolved for 0.12.0:
Failed to resolve: com.tomtom.sdk.location:provider-map-matched:0.12.0
Failed to resolve: com.tomtom.sdk.navigation:navigation:0.12.0
Failed to resolve: com.tomtom.sdk.navigation:ui:0.12.0
Failed to resolve: com.tomtom.sdk.navigation:route-replanner-online:0.12.0
![Screenshot 2023-05-23 at 3 23 53 PM](https://github.com/tomtom-international/tomtom-navigation-android-examples/assets/8468554/778f3a74-7f80-4bc8-a445-4276d15f29dc)

**Comment by joserojas-tomtom** [comment]
Hey @babaosoftware 

I see you are trying to build something with our Navigation SDK, great!

The SDKs are only available via requests, check our README. Contact us and we will happy to help you and your company.

[Contact Us](https://developer.tomtom.com/tomtom-sdk-for-android/request-access)

**Comment by babaosoftware** [comment]
@joserojas-tomtom I have been building apps with the TomTom sdk for quite a while now. I've been in touch with TomTom people for quite some time, and as a matter of fact I was the one suggesting to @ioanakanda-tomtom to create this sample application on github. My problem is that as of now, when I try to rebuild this project (or any other project, for that matter) with the new version of the libraries, either 0.12.0, or 0.22.4, it fails to download some of the libraries, as show in the attached screenshot. It works fine if I go back to 0.3.1617.
![Screenshot 2023-06-08 at 8 08 07 AM](https://github.com/tomtom-international/tomtom-navigation-android-examples/assets/8468554/b9e9e344-abd5-4909-93f1-375d67645fe5)

**Comment by babaosoftware** [comment]
Trying to update to the latest 0.23.0, same problem. Those 4 libraries are not available.
![Screenshot 2023-06-18 at 11 38 40 AM](https://github.com/tomtom-international/tomtom-navigation-android-examples/assets/8468554/86de0d4f-3a21-4ca9-9203-9d5c5db4a9e3)

**Comment by babaosoftware** [comment]
The problem was the access token to the maven repository. Once I generated a new token, it loaded all libraries. I'm currently on version 0.23.0.
