### ISSUE TITLE
Some sdk files not able to syncs !!

### ISSUE THREAD

**Issue by Prashant830** [tomtom-international/tomtom-navigation-android-examples#69]
### Issue - 
When I try to sync latest release version (0.30.1) of navigation sdk of tomtom then some of library is not synced and files are ( I also mention the api key , username , password as well but the same ) - <br>
```com.tomtom.sdk.common:core:0.30.1
com.tomtom.sdk.vehicle:model:0.30.1
com.tomtom.sdk.location:provider-map-matched:0.30.1
com.tomtom.sdk.navigation:navigation-online:0.30.1
com.tomtom.sdk.navigation:ui:0.30.1
com.tomtom.sdk.navigation:route-replanner-online:0.30.1
com.tomtom.sdk.search:common:0.30.1
com.tomtom.sdk.common:net-internal:0.30.1
com.tomtom.sdk.common:collections:0.30.1
com.tomtom.sdk.common:http-handler-internal:0.30.1
com.tomtom.sdk.common:http-framework-binding-internal:0.30.1
```
### Expected -
When I try to sync latest release version (0.30.1) of navigation sdk of tomtom then should syncs all files.

### Screenshot - 
![dependency_error](https://github.com/tomtom-international/tomtom-navigation-android-examples/assets/72181295/1f46a56b-a0a3-4e62-9885-9e79315a230a)

**Comment by foliolo** [comment]
It seems to be resolved. I'm using the latest version 0.36.0 and it is working for me.

**Comment by AristotelispetrosBobas-TomTom** [comment]
Missing artifacts on Artifactory have been added. Latest versions builds are stable.
